title: Lee Teuk Ki
description: Personal Blog
author: Lee Teuk kI
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/leeteukki
about: Freelance developer

baseurl: "https://leeteukki.github.io/snue_patent.github.io/"
url: "https://leeteukki.github.io/snue_patent.github.io/"

allowsearch: true

disqus_shortname: snue_patent
google_analytics: UA-101957512-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
